### ISSUE TITLE
Interval Timer

### ISSUE THREAD

**Issue by BrannanC** [BrannanC/basic_timers#1]
Should work like a stopwatch that runners would use to keep track of lap times.

Needs method to add to list of completed intervals.
Method to retrieve all completed intervals.

**Comment by thesoundfromthesky** [comment]
Good afternoon, Brannan, This is what I wrote
Can you review please? 


class IntervalTime extends Timer {
  completed_intervals = [];
  constructor(on_start, on_end, on_update, update_interval_rate) {
    super(on_start, on_end, on_update, update_interval_rate);
  }

  complete_interval() {
    const elapsed_time = this.get_elapsed_time();

    if (!elapsed_time) {
      throw Error("Start timer first");
    }

    this.complete_intervals.push(elapsed_time);
  }

  retrieve_all_completed_intervals() {
    this.complete_intervals.forEach((e, i) =>
      console.log(`Set ${i + 1}: ${e}`)
    );
  }
}

Thank you!

**Comment by thesoundfromthesky** [comment]
test code

```

function on_start() {
  console.log("start");
}

function on_end() {
  console.log("end");
}

function on_update() {
//   console.log("update");
}
const it = new IntervalTime(on_start, on_end, on_update);

it.start();

const interval_id = setInterval(() => {
  it.complete_interval();
}, 3 * 1000);

setTimeout(() => {
  clearInterval(interval_id);
  it.stop();
  it.retrieve_all_completed_intervals();
}, 10 * 1000);

```

**Comment by BrannanC** [comment]
This is close to what I want, but each interval should be the elapsed time since the last interval.
completed_intervals[0] should be elapsed_time - 0 (first one)
completed_intervals[1] should be elapsed_time since completed_intervals[0]
completed_intervals[2] should be elapsed_time since completed_intervals[1]

Let's make a parameter for on_complete_interval so we can pass a function in like we did with start stop and update.

And go ahead and make a branch and a PR, that will make these reviews a bit easier
